# Generated by Django 5.2.5 on 2025-09-02 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_wishlist_products'),
        ('order', '0002_address_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cart.cart'),
        ),
    ]
