# Generated by Django 5.2.5 on 2025-09-02 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_wishlist_products'),
        ('order', '0003_order_cart_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_fk',
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cart.cart'),
        ),
    ]
